# Generated by Django 6.0.6 on 2026-06-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid_rfid", models.CharField(max_length=100)),
                ("mpn", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=0)),
                ("datasheet_link", models.CharField(max_length=500)),
                ("component_type", models.CharField(max_length=100)),
                ("unit_price", models.FloatField(default=0.0)),
                ("comment", models.CharField(max_length=400)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
