# Generated by Django 6.0.6 on 2026-06-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="component",
            old_name="smd_tht",
            new_name="smd_or_tht",
        ),
    ]
