# Generated by Django 6.0.6 on 2026-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0002_rename_smd_tht_component_smd_or_tht"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="datasheet_url",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
