# Generated by Django 6.0.6 on 2026-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0002_rename_datasheet_link_component_datasheet_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="datasheet_url",
            field=models.URLField(max_length=500),
        ),
    ]
