# Generated by Django 6.0.6 on 2026-06-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0003_alter_component_datasheet_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="component",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="component",
            name="supplier_pn",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
