# Generated by Django 6.0.6 on 2026-06-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0003_component_datasheet_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="unit_price_ht",
            field=models.FloatField(default=0.0),
        ),
    ]
