# Generated by Django 6.0.6 on 2026-06-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0004_component_unit_price_ht"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="image_url",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
