# Generated by Django 6.0.6 on 2026-06-12 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rfid_reader_app",
            "0004_component_description_component_manufacturer_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Tiroclass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drawer_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="component",
            name="component_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="component",
            name="datasheet_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="Drawer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=1)),
                (
                    "tiroclass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawers",
                        to="rfid_reader_app.tiroclass",
                    ),
                ),
            ],
            options={
                "unique_together": {("tiroclass", "number")},
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "column",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                        ]
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="rfid_reader_app.component",
                    ),
                ),
                (
                    "drawer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="rfid_reader_app.drawer",
                    ),
                ),
            ],
            options={
                "unique_together": {("drawer", "row", "column")},
            },
        ),
    ]
