# Generated by Django 6.0.6 on 2026-06-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0005_component_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="image_url",
        ),
    ]
