# Generated by Django 6.0.6 on 2026-06-15 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0005_tiroclass_alter_component_component_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("led", "LED"),
                    ("resistor", "Resistor"),
                    ("capacitor", "Capacitor"),
                    ("inductor", "Inductor"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ComponentSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("led_type", models.CharField(blank=True, max_length=50, null=True)),
                ("max_current_ma", models.FloatField(blank=True, null=True)),
                ("tension_v", models.FloatField(blank=True, null=True)),
                ("value_ohm", models.FloatField(blank=True, null=True)),
                (
                    "capacitor_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("capacitance_microf", models.FloatField(blank=True, null=True)),
                ("inductance_mh", models.FloatField(blank=True, null=True)),
                (
                    "component",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec",
                        to="rfid_reader_app.component",
                    ),
                ),
            ],
        ),
    ]
