# Generated by Django 6.0.6 on 2026-06-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0006_alter_component_component_type_componentspec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="datasheet_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
