# Generated by Django 6.0.6 on 2026-06-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0006_remove_component_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawer",
            name="drawer_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
