# Generated by Django 6.0.6 on 2026-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0007_drawer_drawer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentcriteria",
            name="value",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
