# Generated by Django 6.0.6 on 2026-06-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0008_alter_componentcriteria_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={
                "permissions": [
                    (
                        "change_component_quantity",
                        "May increase or decrease stock levels",
                    )
                ]
            },
        ),
    ]
