# Generated by Django 6.0.6 on 2026-06-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0009_alter_component_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={
                "permissions": [
                    ("change_component_quantity", "Change Component Quantity")
                ]
            },
        ),
    ]
