# Generated by Django 6.0.6 on 2026-06-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0010_alter_component_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={},
        ),
    ]
