# Generated by Django 6.0.6 on 2026-07-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_reader_app", "0011_alter_component_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={
                "permissions": [("can_add_component", "Can add component in database")]
            },
        ),
    ]
