M48
; DRILL file {KiCad 9.0.7} date 2026-06-11T13:29:48+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-11T13:29:48+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X97.11Y-51.6
X102.89Y-51.6
T2
X82.5Y-90.0
X86.0Y-128.0
X114.0Y-128.0
X117.5Y-90.0
M30
